name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install CUnit
      run: sudo apt install -y libcunit1-dev valgrind
    - name: Run Make
      run: make
    - name: Run tests
      run: make check
    - name: Run Valgrind
      run: make memcheck
    - uses: actions/upload-artifact@v3
      with:
        name: Upload artifacts
        path: ./**/[abc]rtifac?/*.log
        if-no-files-found: warn
